// ClientApp/release-manager-vue/src/views/Releases.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import { useRouter } from 'vue-router';
import { base44, type Release, type Project, type Team } from '@/api/base44Client';
import { useLanguage } from '@/composables/useLanguage';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import Card from '@/components/ui/Card.vue';
import CardHeader from '@/components/ui/CardHeader.vue';
import CardTitle from '@/components/ui/CardTitle.vue';
import CardContent from '@/components/ui/CardContent.vue';
import Badge from '@/components/ui/Badge.vue';
import { Search, Plus, Package, Edit, Trash2, Loader2, Calendar } from 'lucide-vue-next';
import { format } from 'date-fns';

const { t, isRTL } = useLanguage();
const router = useRouter();
const queryClient = useQueryClient();

const STATUS_CONFIG = {
  planning: { label: computed(() => t('planning')), color: 'bg-slate-100 text-slate-700' },
  in_progress: { label: computed(() => t('inProgress')), color: 'bg-blue-100 text-blue-700' },
  testing: { label: computed(() => t('testing')), color: 'bg-purple-100 text-purple-700' },
  ready_for_deploy: { label: computed(() => t('readyForDeploy')), color: 'bg-amber-100 text-amber-700' },
  deployed: { label: computed(() => t('deployed')), color: 'bg-emerald-100 text-emerald-700' },
  cancelled: { label: computed(() => t('cancelled')), color: 'bg-rose-100 text-rose-700' },
};

const PRIORITY_CONFIG = {
  low: { label: computed(() => t('low')), color: 'bg-slate-100 text-slate-700' },
  medium: { label: computed(() => t('medium')), color: 'bg-blue-100 text-blue-700' },
  high: { label: computed(() => t('high')), color: 'bg-amber-100 text-amber-700' },
  critical: { label: computed(() => t('critical')), color: 'bg-rose-100 text-rose-700' },
};

const searchQuery = ref('');
const statusFilter = ref<string>('all');

const { data: releases, isLoading } = useQuery({
  queryKey: ['releases'],
  queryFn: () => base44.entities.Release.list(),
});

const { data: projects } = useQuery({
  queryKey: ['projects'],
  queryFn: () => base44.entities.Project.list(),
});

const { data: teams } = useQuery({
  queryKey: ['teams'],
  queryFn: () => base44.entities.Team.list(),
});

const deleteMutation = useMutation({
  mutationFn: (id: string) => base44.entities.Release.delete(id),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['releases'] });
  },
});

const getProjectName = (projectId?: string) => {
  if (!projectId || !projects.value || !Array.isArray(projects.value) || projects.value.length === 0) return t('unassigned');
  const project = projects.value.find((p: Project) => p.id === projectId);
  return project?.name || t('unassigned');
};

const getTeamName = (teamId?: string) => {
  if (!teamId || !teams.value || !Array.isArray(teams.value) || teams.value.length === 0) return t('unassigned');
  const team = teams.value.find((t: Team) => t.id === teamId);
  return team?.name || t('unassigned');
};

const formatDate = (dateString?: string) => {
  if (!dateString) return t('notSet');
  return format(new Date(dateString), 'MMM dd, yyyy');
};

const filteredReleases = computed(() => {
  if (!releases.value || !Array.isArray(releases.value) || releases.value.length === 0) return [];
  
  return releases.value.filter((release: Release) => {
    const matchesSearch =
      !searchQuery.value ||
      release.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      release.version.toLowerCase().includes(searchQuery.value.toLowerCase());
    const matchesStatus = statusFilter.value === 'all' || release.status === statusFilter.value;
    return matchesSearch && matchesStatus;
  });
});
</script>

<template>
  <div
    class="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6"
    :dir="isRTL ? 'rtl' : 'ltr'"
  >
    <div class="max-w-7xl mx-auto">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <h1 class="text-3xl font-bold text-slate-800">{{ t('releases') }}</h1>
          <p class="text-slate-500 mt-1">Manage all your software releases</p>
        </div>
        <Button class="bg-indigo-600 hover:bg-indigo-700 gap-2">
          <Plus class="w-4 h-4" />
          {{ t('newRelease') }}
        </Button>
      </div>

      <!-- Filters -->
      <div class="flex flex-col md:flex-row gap-4 mb-6">
        <div class="relative flex-1 max-w-md">
          <Search
            :class="`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400`"
          />
          <Input
            v-model="searchQuery"
            placeholder="Search releases..."
            :class="isRTL ? 'pr-10' : 'pl-10'"
          />
        </div>
        <select
          v-model="statusFilter"
          class="w-40 h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"
        >
          <option value="all">{{ t('allStatus') }}</option>
          <option v-for="(config, key) in STATUS_CONFIG" :key="key" :value="key">
            {{ config.label.value }}
          </option>
        </select>
      </div>

      <!-- Releases Grid -->
      <div v-if="isLoading" class="flex items-center justify-center h-64">
        <Loader2 class="w-8 h-8 animate-spin text-indigo-600" />
      </div>
      <div v-else-if="filteredReleases.length === 0" class="text-center py-16">
        <Package class="w-16 h-16 mx-auto text-slate-300 mb-4" />
        <h3 class="text-lg font-medium text-slate-600">No releases found</h3>
        <p class="text-slate-400 mt-1">Create your first release to get started</p>
        <Button class="mt-4 bg-indigo-600 hover:bg-indigo-700">
          <Plus :class="`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`" />
          {{ t('createRelease') }}
        </Button>
      </div>
      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div
          v-for="release in filteredReleases"
          :key="release.id"
          class="opacity-0 animate-[fadeIn_0.3s_ease-in_forwards]"
        >
          <Card class="hover:shadow-lg transition-shadow">
            <CardHeader class="pb-3">
              <div class="flex items-start justify-between">
                <div class="flex items-center gap-3">
                  <div class="w-10 h-10 rounded-lg bg-indigo-100 flex items-center justify-center">
                    <Package class="w-5 h-5 text-indigo-600" />
                  </div>
                  <div>
                    <CardTitle class="text-lg">{{ release.name }}</CardTitle>
                    <p class="text-sm text-slate-500">v{{ release.version }}</p>
                  </div>
                </div>
                <div class="flex gap-1">
                  <Button variant="ghost" size="icon">
                    <Edit class="w-4 h-4 text-slate-400" />
                  </Button>
                  <Button variant="ghost" size="icon" @click="deleteMutation.mutate(release.id)">
                    <Trash2 class="w-4 h-4 text-rose-400" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <p v-if="release.description" class="text-sm text-slate-500 mb-4 line-clamp-2">
                {{ release.description }}
              </p>
              <div class="space-y-2 mb-4">
                <div class="flex items-center gap-2 text-sm">
                  <Calendar class="w-4 h-4 text-slate-400" />
                  <span class="text-slate-600">{{ formatDate(release.scheduledDate) }}</span>
                </div>
                <div class="flex items-center gap-2 text-sm">
                  <span class="text-slate-500">Project:</span>
                  <span class="text-slate-700 font-medium">{{ getProjectName(release.projectId) }}</span>
                </div>
                <div class="flex items-center gap-2 text-sm">
                  <span class="text-slate-500">Team:</span>
                  <span class="text-slate-700 font-medium">{{ getTeamName(release.teamId) }}</span>
                </div>
              </div>
              <div class="flex items-center justify-between">
                <Badge :class="STATUS_CONFIG[release.status]?.color">
                  {{ STATUS_CONFIG[release.status]?.label.value }}
                </Badge>
                <Badge :class="PRIORITY_CONFIG[release.priority]?.color">
                  {{ PRIORITY_CONFIG[release.priority]?.label.value }}
                </Badge>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>

// ClientApp/release-manager/src/pages/Releases.jsx
﻿import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
    Plus, Search, Filter, Package, Rocket, Clock,
    CheckCircle, XCircle, AlertTriangle, Loader2, List, Grid
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useLanguage } from '../Layout';

import ReleaseCard from '../components/releases/ReleaseCard';
import ReleaseForm from '../components/releases/ReleaseForm';
import ReleaseDetails from '../components/releases/ReleaseDetails';

export default function Releases() {
    const { t, isRTL } = useLanguage();

    const STATUS_TABS = [
        { value: 'all', label: t('all'), icon: Package },
        { value: 'in_progress', label: t('inProgress'), icon: Clock },
        { value: 'ready_for_deployment', label: t('readyForDeploy'), icon: Rocket },
        { value: 'deployed', label: t('deployed'), icon: CheckCircle },
        { value: 'cancelled', label: t('cancelled'), icon: XCircle }
    ];
    const [searchQuery, setSearchQuery] = useState('');
    const [statusFilter, setStatusFilter] = useState('all');
    const [showForm, setShowForm] = useState(false);
    const [editingRelease, setEditingRelease] = useState(null);
    const [selectedRelease, setSelectedRelease] = useState(null);
    const [generatedNotes, setGeneratedNotes] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    const queryClient = useQueryClient();

    // Check URL for edit param
    useEffect(() => {
        const urlParams = new URLSearchParams(window.location.search);
        const editId = urlParams.get('edit');
        if (editId) {
            base44.entities.Release.filter({ id: editId }).then(releases => {
                if (releases.length > 0) {
                    setEditingRelease(releases[0]);
                    setShowForm(true);
                }
            });
        }
    }, []);

    const { data: releases = [], isLoading } = useQuery({
        queryKey: ['releases'],
        queryFn: () => base44.entities.Release.list('-created_date')
    });

    const { data: teams = [] } = useQuery({
        queryKey: ['teams'],
        queryFn: () => base44.entities.Team.list()
    });

    const { data: projects = [] } = useQuery({
        queryKey: ['projects'],
        queryFn: () => base44.entities.Project.list()
    });

    const { data: releaseItems = [] } = useQuery({
        queryKey: ['releaseItems', selectedRelease?.id],
        queryFn: () => selectedRelease
            ? base44.entities.ReleaseItem.filter({ release_id: selectedRelease.id })
            : [],
        enabled: !!selectedRelease
    });

    const createMutation = useMutation({
        mutationFn: (data) => base44.entities.Release.create(data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['releases'] });
            setShowForm(false);
            setEditingRelease(null);
        }
    });

    const updateMutation = useMutation({
        mutationFn: ({ id, data }) => base44.entities.Release.update(id, data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['releases'] });
            setShowForm(false);
            setEditingRelease(null);
        }
    });

    const handleSave = async (data) => {
        if (editingRelease) {
            updateMutation.mutate({ id: editingRelease.id, data });
        } else {
            createMutation.mutate(data);
        }
    };

    const handleGenerateNotes = async () => {
        if (!selectedRelease || releaseItems.length === 0) return;

        setIsGenerating(true);
        const itemsSummary = releaseItems.map(item =>
            `- [${item.type.toUpperCase()}] ${item.title}: ${item.description || 'No description'}`
        ).join('\n');

        const response = await base44.integrations.Core.InvokeLLM({
            prompt: `Generate professional release notes for version ${selectedRelease.version} of "${selectedRelease.name}".
      
Release Description: ${selectedRelease.description || 'N/A'}

Items included in this release:
${itemsSummary}

Please create well-formatted release notes that:
1. Start with a brief overview
2. Group changes by type (Features, Bug Fixes, Improvements, etc.)
3. Highlight key updates and new functionalities
4. Mention any breaking changes prominently
5. Use markdown formatting`,
        });

        setGeneratedNotes(response);
        setIsGenerating(false);
    };

    const handleSaveNotes = async (notes) => {
        if (!selectedRelease) return;
        await base44.entities.Release.update(selectedRelease.id, { release_notes: notes });
        queryClient.invalidateQueries({ queryKey: ['releases'] });
        setSelectedRelease(null);
        setGeneratedNotes('');
    };

    const getProject = (id) => projects.find(p => p.id === id);
    const getTeam = (id) => teams.find(t => t.id === id);

    // Filter releases
    const filteredReleases = releases.filter(release => {
        const matchesSearch = !searchQuery ||
            release.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            release.version.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesStatus = statusFilter === 'all' || release.status === statusFilter;
        return matchesSearch && matchesStatus;
    });

    if (showForm) {
        return (
            <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
                <div className="max-w-7xl mx-auto">
                    <ReleaseForm
                        release={editingRelease}
                        projects={projects}
                        teams={teams}
                        onSave={handleSave}
                        onCancel={() => {
                            setShowForm(false);
                            setEditingRelease(null);
                        }}
                        isLoading={createMutation.isPending || updateMutation.isPending}
                        t={t}
                    />
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
            <div className="max-w-7xl mx-auto">
                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                    <div>
                        <h1 className="text-3xl font-bold text-slate-800">{t('releases')}</h1>
                        <p className="text-slate-500 mt-1">{t('manageReleases')}</p>
                    </div>
                    <Button
                        onClick={() => setShowForm(true)}
                        className="bg-indigo-600 hover:bg-indigo-700 gap-2"
                    >
                        <Plus className="w-4 h-4" />
                        {t('newRelease')}
                    </Button>
                </div>

                {/* Filters */}
                <div className="flex flex-col md:flex-row gap-4 mb-6">
                    <div className="relative flex-1 max-w-md">
                        <Search className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400`} />
                        <Input
                            placeholder={t('searchReleases')}
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className={isRTL ? 'pr-10' : 'pl-10'}
                        />
                    </div>
                    <Tabs value={statusFilter} onValueChange={setStatusFilter}>
                        <TabsList>
                            {STATUS_TABS.map(tab => (
                                <TabsTrigger key={tab.value} value={tab.value} className="gap-2">
                                    <tab.icon className="w-4 h-4" />
                                    <span className="hidden sm:inline">{tab.label}</span>
                                </TabsTrigger>
                            ))}
                        </TabsList>
                    </Tabs>
                </div>

                {/* Release List */}
                {isLoading ? (
                    <div className="flex items-center justify-center h-64">
                        <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
                    </div>
                ) : filteredReleases.length === 0 ? (
                    <div className="text-center py-16">
                        <Package className="w-16 h-16 mx-auto text-slate-300 mb-4" />
                        <h3 className="text-lg font-medium text-slate-600">{t('noReleasesFound')}</h3>
                        <p className="text-slate-400 mt-1">
                            {searchQuery || statusFilter !== 'all'
                                ? t('tryAdjustingFilters')
                                : t('createFirstRelease')}
                        </p>
                        {!searchQuery && statusFilter === 'all' && (
                            <Button
                                onClick={() => setShowForm(true)}
                                className="mt-4 bg-indigo-600 hover:bg-indigo-700"
                            >
                                <Plus className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
                                {t('createRelease')}
                            </Button>
                        )}
                    </div>
                ) : (
                    <motion.div
                        className="grid gap-4"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                    >
                        <AnimatePresence>
                            {filteredReleases.map((release, index) => (
                                <motion.div
                                    key={release.id}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -20 }}
                                    transition={{ delay: index * 0.05 }}
                                >
                                    <ReleaseCard
                                        release={release}
                                        project={getProject(release.project_id)}
                                        team={getTeam(release.team_id)}
                                        onClick={() => setSelectedRelease(release)}
                                    />
                                </motion.div>
                            ))}
                        </AnimatePresence>
                    </motion.div>
                )}

                {/* Release Details Modal */}
                {selectedRelease && (
                    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
                        <motion.div
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            className="w-full max-w-3xl"
                        >
                            <ReleaseDetails
                                release={selectedRelease}
                                project={getProject(selectedRelease.project_id)}
                                team={getTeam(selectedRelease.team_id)}
                                releaseItems={releaseItems}
                                onClose={() => {
                                    setSelectedRelease(null);
                                    setGeneratedNotes('');
                                }}
                                onEdit={() => {
                                    setEditingRelease(selectedRelease);
                                    setSelectedRelease(null);
                                    setShowForm(true);
                                }}
                                onGenerateNotes={handleGenerateNotes}
                                isGenerating={isGenerating}
                                generatedNotes={generatedNotes}
                                onSaveNotes={handleSaveNotes}
                            />
                        </motion.div>
                    </div>
                )}
            </div>
        </div>
    );
}
