// ClientApp/release-manager-vue/src/views/ReleaseItems.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import { base44, type ReleaseItem, type Release } from '@/api/base44Client';
import { useLanguage } from '@/composables/useLanguage';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import Card from '@/components/ui/Card.vue';
import CardHeader from '@/components/ui/CardHeader.vue';
import CardTitle from '@/components/ui/CardTitle.vue';
import CardContent from '@/components/ui/CardContent.vue';
import Badge from '@/components/ui/Badge.vue';
import { Search, Plus, ListTodo, Edit, Trash2, Loader2, User, Hash } from 'lucide-vue-next';

const { t, isRTL } = useLanguage();
const queryClient = useQueryClient();

const TYPE_CONFIG = {
  feature: { label: computed(() => t('feature')), color: 'bg-blue-100 text-blue-700', icon: '✨' },
  bug_fix: { label: computed(() => t('bugFix')), color: 'bg-rose-100 text-rose-700', icon: '🐛' },
  improvement: { label: computed(() => t('improvement')), color: 'bg-purple-100 text-purple-700', icon: '⚡' },
  breaking_change: { label: computed(() => t('breakingChange')), color: 'bg-amber-100 text-amber-700', icon: '⚠️' },
  security: { label: computed(() => t('security')), color: 'bg-emerald-100 text-emerald-700', icon: '🔒' },
  documentation: { label: computed(() => t('documentation')), color: 'bg-slate-100 text-slate-700', icon: '📚' },
};

const STATUS_CONFIG = {
  pending: { label: computed(() => t('pending')), color: 'bg-slate-100 text-slate-700' },
  in_progress: { label: computed(() => t('inProgress')), color: 'bg-blue-100 text-blue-700' },
  completed: { label: computed(() => t('completed')), color: 'bg-emerald-100 text-emerald-700' },
};

const searchQuery = ref('');
const typeFilter = ref<string>('all');

const { data: items, isLoading } = useQuery({
  queryKey: ['releaseitems'],
  queryFn: () => base44.entities.ReleaseItem.list(),
});

const { data: releases } = useQuery({
  queryKey: ['releases'],
  queryFn: () => base44.entities.Release.list(),
});

const deleteMutation = useMutation({
  mutationFn: (id: string) => base44.entities.ReleaseItem.delete(id),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['releaseitems'] });
  },
});

const getReleaseName = (releaseId?: string) => {
  if (!releaseId || !releases.value || !Array.isArray(releases.value) || releases.value.length === 0) return t('unassigned');
  const release = releases.value.find((r: Release) => r.id === releaseId);
  return release ? `${release.name} (v${release.version})` : t('unassigned');
};

const filteredItems = computed(() => {
  if (!items.value || !Array.isArray(items.value) || items.value.length === 0) return [];
  
  return items.value.filter((item: ReleaseItem) => {
    const matchesSearch =
      !searchQuery.value ||
      item.title.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      (item.ticketNumber && item.ticketNumber.toLowerCase().includes(searchQuery.value.toLowerCase()));
    const matchesType = typeFilter.value === 'all' || item.type === typeFilter.value;
    return matchesSearch && matchesType;
  });
});
</script>

<template>
  <div
    class="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6"
    :dir="isRTL ? 'rtl' : 'ltr'"
  >
    <div class="max-w-7xl mx-auto">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <h1 class="text-3xl font-bold text-slate-800">{{ t('releaseItems') }}</h1>
          <p class="text-slate-500 mt-1">{{ t('featuresAndBugFixes') }}</p>
        </div>
        <Button class="bg-indigo-600 hover:bg-indigo-700 gap-2">
          <Plus class="w-4 h-4" />
          {{ t('addItem') }}
        </Button>
      </div>

      <!-- Filters -->
      <div class="flex flex-col md:flex-row gap-4 mb-6">
        <div class="relative flex-1 max-w-md">
          <Search
            :class="`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400`"
          />
          <Input
            v-model="searchQuery"
            :placeholder="t('searchItems')"
            :class="isRTL ? 'pr-10' : 'pl-10'"
          />
        </div>
        <select
          v-model="typeFilter"
          class="w-40 h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"
        >
          <option value="all">{{ t('allTypes') }}</option>
          <option v-for="(config, key) in TYPE_CONFIG" :key="key" :value="key">
            {{ config.icon }} {{ config.label.value }}
          </option>
        </select>
      </div>

      <!-- Items List -->
      <div v-if="isLoading" class="flex items-center justify-center h-64">
        <Loader2 class="w-8 h-8 animate-spin text-indigo-600" />
      </div>
      <div v-else-if="filteredItems.length === 0" class="text-center py-16">
        <ListTodo class="w-16 h-16 mx-auto text-slate-300 mb-4" />
        <h3 class="text-lg font-medium text-slate-600">{{ t('noItemsFound') }}</h3>
        <p class="text-slate-400 mt-1">{{ t('addFirstItem') }}</p>
        <Button class="mt-4 bg-indigo-600 hover:bg-indigo-700">
          <Plus :class="`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`" />
          {{ t('addItem') }}
        </Button>
      </div>
      <div v-else class="space-y-4">
        <div
          v-for="item in filteredItems"
          :key="item.id"
          class="opacity-0 animate-[fadeIn_0.3s_ease-in_forwards]"
        >
          <Card class="hover:shadow-lg transition-shadow">
            <CardContent class="pt-6">
              <div class="flex items-start justify-between">
                <div class="flex-1">
                  <div class="flex items-center gap-2 mb-2">
                    <Badge :class="TYPE_CONFIG[item.type]?.color">
                      {{ TYPE_CONFIG[item.type]?.icon }} {{ TYPE_CONFIG[item.type]?.label.value }}
                    </Badge>
                    <Badge :class="STATUS_CONFIG[item.status]?.color">
                      {{ STATUS_CONFIG[item.status]?.label.value }}
                    </Badge>
                  </div>
                  <h3 class="text-lg font-semibold text-slate-800 mb-2">{{ item.title }}</h3>
                  <p v-if="item.description" class="text-sm text-slate-600 mb-3">
                    {{ item.description }}
                  </p>
                  <div class="flex flex-wrap items-center gap-4 text-sm text-slate-500">
                    <div v-if="item.ticketNumber" class="flex items-center gap-1">
                      <Hash class="w-4 h-4" />
                      <span>{{ item.ticketNumber }}</span>
                    </div>
                    <div v-if="item.assignedTo" class="flex items-center gap-1">
                      <User class="w-4 h-4" />
                      <span>{{ item.assignedTo }}</span>
                    </div>
                    <div class="flex items-center gap-1">
                      <span>Release:</span>
                      <span class="font-medium">{{ getReleaseName(item.releaseId) }}</span>
                    </div>
                  </div>
                </div>
                <div class="flex gap-1">
                  <Button variant="ghost" size="icon">
                    <Edit class="w-4 h-4 text-slate-400" />
                  </Button>
                  <Button variant="ghost" size="icon" @click="deleteMutation.mutate(item.id)">
                    <Trash2 class="w-4 h-4 text-rose-400" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>

// ClientApp/release-manager/src/pages/ReleaseItems.jsx
﻿import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
    Plus, Search, Trash2, Edit, Bug, Zap, Sparkles,
    AlertTriangle, Shield, BookOpen, Loader2, Filter
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from "@/lib/utils";
import { useLanguage } from '../Layout';

import ReleaseItemForm from '../components/releases/ReleaseItemForm';

export default function ReleaseItems() {
    const { t, isRTL } = useLanguage();

    const ITEM_TYPE_CONFIG = {
        feature: { label: t('feature'), icon: Zap, color: 'text-blue-600 bg-blue-50 border-blue-200' },
        bug_fix: { label: t('bugFix'), icon: Bug, color: 'text-rose-600 bg-rose-50 border-rose-200' },
        improvement: { label: t('improvement'), icon: Sparkles, color: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
        breaking_change: { label: t('breakingChange'), icon: AlertTriangle, color: 'text-amber-600 bg-amber-50 border-amber-200' },
        security: { label: t('security'), icon: Shield, color: 'text-purple-600 bg-purple-50 border-purple-200' },
        documentation: { label: t('documentation'), icon: BookOpen, color: 'text-slate-600 bg-slate-50 border-slate-200' }
    };

    const STATUS_CONFIG = {
        pending: { label: t('pending'), color: 'bg-slate-100 text-slate-600' },
        in_progress: { label: t('inProgress'), color: 'bg-blue-100 text-blue-600' },
        completed: { label: t('completed'), color: 'bg-emerald-100 text-emerald-600' },
        cancelled: { label: t('cancelled'), color: 'bg-rose-100 text-rose-600' }
    };
    const [searchQuery, setSearchQuery] = useState('');
    const [typeFilter, setTypeFilter] = useState('all');
    const [releaseFilter, setReleaseFilter] = useState('all');
    const [showForm, setShowForm] = useState(false);
    const [editingItem, setEditingItem] = useState(null);

    const queryClient = useQueryClient();

    const { data: items = [], isLoading } = useQuery({
        queryKey: ['releaseItems'],
        queryFn: () => base44.entities.ReleaseItem.list('-created_date')
    });

    const { data: releases = [] } = useQuery({
        queryKey: ['releases'],
        queryFn: () => base44.entities.Release.list()
    });

    const createMutation = useMutation({
        mutationFn: (data) => base44.entities.ReleaseItem.create(data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['releaseItems'] });
            setShowForm(false);
            setEditingItem(null);
        }
    });

    const updateMutation = useMutation({
        mutationFn: ({ id, data }) => base44.entities.ReleaseItem.update(id, data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['releaseItems'] });
            setShowForm(false);
            setEditingItem(null);
        }
    });

    const deleteMutation = useMutation({
        mutationFn: (id) => base44.entities.ReleaseItem.delete(id),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['releaseItems'] });
        }
    });

    const handleSave = async (data) => {
        if (editingItem) {
            updateMutation.mutate({ id: editingItem.id, data });
        } else {
            createMutation.mutate(data);
        }
    };

    const getReleaseName = (id) => {
        const release = releases.find(r => r.id === id);
        return release ? `${release.name} (v${release.version})` : 'Unassigned';
    };

    // Filter items
    const filteredItems = items.filter(item => {
        const matchesSearch = !searchQuery ||
            item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
            (item.description && item.description.toLowerCase().includes(searchQuery.toLowerCase()));
        const matchesType = typeFilter === 'all' || item.type === typeFilter;
        const matchesRelease = releaseFilter === 'all' || item.release_id === releaseFilter;
        return matchesSearch && matchesType && matchesRelease;
    });

    if (showForm) {
        return (
            <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
                <div className="max-w-7xl mx-auto">
                    <ReleaseItemForm
                        item={editingItem}
                        releaseId={releaseFilter !== 'all' ? releaseFilter : ''}
                        onSave={handleSave}
                        onCancel={() => {
                            setShowForm(false);
                            setEditingItem(null);
                        }}
                        isLoading={createMutation.isPending || updateMutation.isPending}
                        t={t}
                    />
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
            <div className="max-w-7xl mx-auto">
                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                    <div>
                        <h1 className="text-3xl font-bold text-slate-800">{t('releaseItems')}</h1>
                        <p className="text-slate-500 mt-1">{t('featuresAndBugFixes')}</p>
                    </div>
                    <Button
                        onClick={() => setShowForm(true)}
                        className="bg-indigo-600 hover:bg-indigo-700 gap-2"
                    >
                        <Plus className="w-4 h-4" />
                        {t('addItem')}
                    </Button>
                </div>

                {/* Filters */}
                <div className="flex flex-col md:flex-row gap-4 mb-6">
                    <div className="relative flex-1 max-w-md">
                        <Search className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400`} />
                        <Input
                            placeholder={t('searchItems')}
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className={isRTL ? 'pr-10' : 'pl-10'}
                        />
                    </div>
                    <div className="flex gap-3">
                        <Select value={typeFilter} onValueChange={setTypeFilter}>
                            <SelectTrigger className="w-40">
                                <Filter className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
                                <SelectValue placeholder={t('type')} />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">{t('allTypes')}</SelectItem>
                                {Object.entries(ITEM_TYPE_CONFIG).map(([value, config]) => (
                                    <SelectItem key={value} value={value}>{config.label}</SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                        <Select value={releaseFilter} onValueChange={setReleaseFilter}>
                            <SelectTrigger className="w-48">
                                <SelectValue placeholder={t('releases')} />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">{t('allReleases')}</SelectItem>
                                {releases.map(release => (
                                    <SelectItem key={release.id} value={release.id}>
                                        {release.name} (v{release.version})
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>
                </div>

                {/* Items List */}
                {isLoading ? (
                    <div className="flex items-center justify-center h-64">
                        <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
                    </div>
                ) : filteredItems.length === 0 ? (
                    <div className="text-center py-16">
                        <Zap className="w-16 h-16 mx-auto text-slate-300 mb-4" />
                        <h3 className="text-lg font-medium text-slate-600">{t('noItemsFound')}</h3>
                        <p className="text-slate-400 mt-1">
                            {searchQuery || typeFilter !== 'all' || releaseFilter !== 'all'
                                ? t('tryAdjustingFilters')
                                : t('addFirstItem')}
                        </p>
                        {!searchQuery && typeFilter === 'all' && releaseFilter === 'all' && (
                            <Button
                                onClick={() => setShowForm(true)}
                                className="mt-4 bg-indigo-600 hover:bg-indigo-700"
                            >
                                <Plus className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
                                {t('addItem')}
                            </Button>
                        )}
                    </div>
                ) : (
                    <motion.div
                        className="grid gap-3"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                    >
                        <AnimatePresence>
                            {filteredItems.map((item, index) => {
                                const typeConfig = ITEM_TYPE_CONFIG[item.type] || ITEM_TYPE_CONFIG.feature;
                                const statusConfig = STATUS_CONFIG[item.status] || STATUS_CONFIG.pending;
                                const Icon = typeConfig.icon;

                                return (
                                    <motion.div
                                        key={item.id}
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        exit={{ opacity: 0, y: -20 }}
                                        transition={{ delay: index * 0.03 }}
                                    >
                                        <Card className="p-4 hover:shadow-md transition-shadow">
                                            <div className="flex items-start gap-4">
                                                <div className={cn(
                                                    "p-2 rounded-lg shrink-0",
                                                    typeConfig.color.split(' ').slice(1).join(' ')
                                                )}>
                                                    <Icon className={cn("w-5 h-5", typeConfig.color.split(' ')[0])} />
                                                </div>
                                                <div className="flex-1 min-w-0">
                                                    <div className="flex items-start justify-between gap-4">
                                                        <div>
                                                            <h3 className="font-semibold text-slate-800">{item.title}</h3>
                                                            {item.description && (
                                                                <p className="text-sm text-slate-500 mt-1 line-clamp-2">
                                                                    {item.description}
                                                                </p>
                                                            )}
                                                            <div className="flex flex-wrap items-center gap-2 mt-2">
                                                                <Badge className={cn("text-xs border", typeConfig.color)}>
                                                                    {typeConfig.label}
                                                                </Badge>
                                                                <Badge className={cn("text-xs", statusConfig.color)}>
                                                                    {statusConfig.label}
                                                                </Badge>
                                                                {item.ticket_number && (
                                                                    <Badge variant="outline" className="text-xs">
                                                                        {item.ticket_number}
                                                                    </Badge>
                                                                )}
                                                                {item.release_id && (
                                                                    <span className="text-xs text-slate-400">
                                                                        {getReleaseName(item.release_id)}
                                                                    </span>
                                                                )}
                                                            </div>
                                                        </div>
                                                        <div className="flex items-center gap-1 shrink-0">
                                                            <Button
                                                                variant="ghost"
                                                                size="icon"
                                                                onClick={() => {
                                                                    setEditingItem(item);
                                                                    setShowForm(true);
                                                                }}
                                                            >
                                                                <Edit className="w-4 h-4 text-slate-400" />
                                                            </Button>
                                                            <Button
                                                                variant="ghost"
                                                                size="icon"
                                                                onClick={() => deleteMutation.mutate(item.id)}
                                                            >
                                                                <Trash2 className="w-4 h-4 text-rose-400" />
                                                            </Button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </Card>
                                    </motion.div>
                                );
                            })}
                        </AnimatePresence>
                    </motion.div>
                )}
            </div>
        </div>
    );
}
