// ClientApp/release-manager-vue/src/views/Teams.vue
<script lang="ts">
import { defineComponent, ref, computed } from 'vue';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import { base44, type Team } from '@/api/base44Client';
import { useLanguage } from '@/composables/useLanguage';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import Card from '@/components/ui/Card.vue';
import CardHeader from '@/components/ui/CardHeader.vue';
import CardTitle from '@/components/ui/CardTitle.vue';
import CardContent from '@/components/ui/CardContent.vue';
import { Search, Plus, Users, Edit, Trash2, Loader2, User } from 'lucide-vue-next';
import Dialog from '@/components/ui/Dialog.vue';
import DialogContent from '@/components/ui/DialogContent.vue';
import DialogHeader from '@/components/ui/DialogHeader.vue';
import DialogTitle from '@/components/ui/DialogTitle.vue';
import DialogFooter from '@/components/ui/DialogFooter.vue';

export default defineComponent({
  name: 'TeamsView',
  components: {
    Button,
    Input,
    Card,
    CardHeader,
    CardTitle,
    CardContent,
    Search,
    Plus,
    Users,
    Edit,
    Trash2,
    Loader2,
    User,
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
  },

  setup() {
    const { t, isRTL } = useLanguage();
    const queryClient = useQueryClient();

    const searchQuery = ref('');
    const showDialog = ref(false);
    const editingTeam = ref<Team | null>(null);
    const formData = ref({
      name: '',
      description: '',
      lead: '',
      membersCount: 0,
      color: '#6366f1',
    });

    const { data: teams, isLoading } = useQuery({
      queryKey: ['teams'],
      queryFn: async () => {
        const result = await base44.entities.Team.list();
        return Array.isArray(result) ? result : (result?.data || result?.value || []);
      },
      enabled: true,
      staleTime: 0,
      gcTime: 0,
    });

    const createMutation = useMutation({
      mutationFn: (data: Partial<Team>) => base44.entities.Team.create(data),
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['teams'] });
        handleCloseDialog();
      },
    });

    const updateMutation = useMutation({
      mutationFn: ({ id, data }: { id: string; data: Partial<Team> }) =>
        base44.entities.Team.update(id, data),
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['teams'] });
        handleCloseDialog();
      },
    });

    const deleteMutation = useMutation({
      mutationFn: (id: string) => base44.entities.Team.delete(id),
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['teams'] });
      },
    });

    const filteredTeams = computed((): Team[] => {
      if (!teams.value || !Array.isArray(teams.value) || teams.value.length === 0) {
        return [];
      }
      
      return teams.value.filter((team: Team) => {
        const matchesSearch =
          !searchQuery.value ||
          team.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
          (team.lead && team.lead.toLowerCase().includes(searchQuery.value.toLowerCase()));
        return matchesSearch;
      });
    });

    const handleOpenDialog = (team?: Team): void => {
      if (team) {
        editingTeam.value = team;
        formData.value = {
          name: team.name || '',
          description: team.description || '',
          lead: team.lead || '',
          membersCount: team.membersCount || 0,
          color: team.color || '#6366f1',
        };
      } else {
        editingTeam.value = null;
        formData.value = {
          name: '',
          description: '',
          lead: '',
          membersCount: 0,
          color: '#6366f1',
        };
      }
      showDialog.value = true;
    };

    const handleCloseDialog = (): void => {
      showDialog.value = false;
      editingTeam.value = null;
      formData.value = {
        name: '',
        description: '',
        lead: '',
        membersCount: 0,
        color: '#6366f1',
      };
    };

    const handleSave = (): void => {
      if (editingTeam.value) {
        updateMutation.mutate({
          id: editingTeam.value.id,
          data: formData.value,
        });
      } else {
        createMutation.mutate(formData.value);
      }
    };

    return {
      // State
      searchQuery,
      showDialog,
      editingTeam,
      formData,
      // Data
      teams,
      isLoading,
      // Mutations
      createMutation,
      updateMutation,
      deleteMutation,
      // Computed
      filteredTeams,
      // Methods
      handleOpenDialog,
      handleCloseDialog,
      handleSave,
      // Utilities
      t,
      isRTL,
    };
  },

  mounted() {
    console.log('🎯 Teams page mounted - ready to display data');
  },
});
</script>

<template>
  <div
    class="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6"
    :dir="isRTL ? 'rtl' : 'ltr'"
  >
    <div class="max-w-7xl mx-auto">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <h1 class="text-3xl font-bold text-slate-800">{{ t('teams') }}</h1>
          <p class="text-slate-500 mt-1">{{ t('manageTeams') }}</p>
        </div>
        <Button @click="handleOpenDialog()" class="bg-indigo-600 hover:bg-indigo-700 gap-2">
          <Plus class="w-4 h-4" />
          {{ t('newTeam') }}
        </Button>
      </div>

      <!-- Search -->
      <div class="relative max-w-md mb-6">
        <Search
          :class="`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400`"
        />
        <Input
          v-model="searchQuery"
          :placeholder="t('searchTeams')"
          :class="isRTL ? 'pr-10' : 'pl-10'"
        />
      </div>

      <!-- Teams Grid -->
      <div v-if="isLoading" class="flex items-center justify-center h-64">
        <Loader2 class="w-8 h-8 animate-spin text-indigo-600" />
      </div>
      <div v-else-if="filteredTeams.length === 0" class="text-center py-16">
        <Users class="w-16 h-16 mx-auto text-slate-300 mb-4" />
        <h3 class="text-lg font-medium text-slate-600">{{ t('noTeamsFound') }}</h3>
        <p class="text-slate-400 mt-1">{{ t('createFirstTeam') }}</p>
        <Button class="mt-4 bg-indigo-600 hover:bg-indigo-700">
          <Plus :class="`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`" />
          {{ t('createTeam') }}
        </Button>
      </div>
      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div
          v-for="team in filteredTeams"
          :key="team.id"
          class="fade-in-card"
        >
          <Card class="hover:shadow-lg transition-shadow">
            <CardHeader class="pb-3">
              <div class="flex items-start justify-between">
                <div class="flex items-center gap-3">
                  <div
                    class="w-10 h-10 rounded-lg flex items-center justify-center"
                    :style="{ backgroundColor: team.color || '#6366f1' }"
                  >
                    <Users class="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <CardTitle class="text-lg">{{ team.name }}</CardTitle>
                    <p v-if="team.lead" class="text-sm text-slate-500 flex items-center gap-1 mt-0.5">
                      <User class="w-3 h-3" />
                      {{ team.lead }}
                    </p>
                  </div>
                </div>
                <div class="flex gap-1">
                  <Button variant="ghost" size="icon" @click="handleOpenDialog(team)">
                    <Edit class="w-4 h-4 text-slate-400" />
                  </Button>
                  <Button variant="ghost" size="icon" @click="deleteMutation.mutate(team.id)">
                    <Trash2 class="w-4 h-4 text-rose-400" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <p v-if="team.description" class="text-sm text-slate-500 mb-4 line-clamp-2">
                {{ team.description }}
              </p>
              <div class="flex items-center justify-between">
                <div class="flex items-center gap-2 text-sm text-slate-600">
                  <Users class="w-4 h-4" />
                  <span>{{ team.membersCount }} {{ t('members') }}</span>
                </div>
                <div
                  v-if="team.color"
                  class="w-6 h-6 rounded-full border-2 border-white shadow-sm"
                  :style="{ backgroundColor: team.color }"
                ></div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>

    <!-- Create/Edit Team Dialog -->
    <Dialog :open="showDialog" @update:open="showDialog = $event">
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            {{ editingTeam ? 'Edit Team' : 'New Team' }}
          </DialogTitle>
        </DialogHeader>
        <div class="space-y-4 py-4">
          <div class="space-y-2">
            <label class="text-sm font-medium">Team Name</label>
            <Input v-model="formData.name" type="text" placeholder="Team Name" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium">Description</label>
            <Input v-model="formData.description" type="text" placeholder="Description" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium">Team Lead</label>
            <Input v-model="formData.lead" type="text" placeholder="Lead Name" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium">Members Count</label>
            <Input v-model.number="formData.membersCount" type="number" placeholder="0" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium">Color</label>
            <Input v-model="formData.color" type="color" />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" @click="handleCloseDialog">Cancel</Button>
          <Button @click="handleSave" class="bg-indigo-600 hover:bg-indigo-700">
            {{ editingTeam ? 'Update' : 'Create' }}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
</template>

<style scoped>
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.fade-in-card {
  animation: fadeIn 0.3s ease-in forwards;
}
</style>

// ClientApp/release-manager/src/pages/Teams.jsx
﻿import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import {
    Plus, Search, Users, Edit, Trash2, Loader2,
    User, Palette, Save, X
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from "@/lib/utils";
import { useLanguage } from '../Layout';

const TEAM_COLORS = [
    '#6366f1', '#8b5cf6', '#a855f7', '#d946ef', '#ec4899',
    '#f43f5e', '#ef4444', '#f97316', '#f59e0b', '#eab308',
    '#84cc16', '#22c55e', '#10b981', '#14b8a6', '#06b6d4'
];

export default function Teams() {
    const { t, isRTL } = useLanguage();
    const [searchQuery, setSearchQuery] = useState('');
    const [showDialog, setShowDialog] = useState(false);
    const [editingTeam, setEditingTeam] = useState(null);
    const [formData, setFormData] = useState({
        name: '',
        description: '',
        lead: '',
        members_count: 1,
        color: TEAM_COLORS[0]
    });

    const queryClient = useQueryClient();

    const { data: teams = [], isLoading } = useQuery({
        queryKey: ['teams'],
        queryFn: () => base44.entities.Team.list('-created_date')
    });

    const { data: releases = [] } = useQuery({
        queryKey: ['releases'],
        queryFn: () => base44.entities.Release.list()
    });

    const createMutation = useMutation({
        mutationFn: (data) => base44.entities.Team.create(data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['teams'] });
            handleCloseDialog();
        }
    });

    const updateMutation = useMutation({
        mutationFn: ({ id, data }) => base44.entities.Team.update(id, data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['teams'] });
            handleCloseDialog();
        }
    });

    const deleteMutation = useMutation({
        mutationFn: (id) => base44.entities.Team.delete(id),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['teams'] });
        }
    });

    const handleOpenDialog = (team = null) => {
        if (team) {
            setEditingTeam(team);
            setFormData({
                name: team.name || '',
                description: team.description || '',
                lead: team.lead || '',
                members_count: team.members_count || 1,
                color: team.color || TEAM_COLORS[0]
            });
        } else {
            setEditingTeam(null);
            setFormData({
                name: '',
                description: '',
                lead: '',
                members_count: 1,
                color: TEAM_COLORS[Math.floor(Math.random() * TEAM_COLORS.length)]
            });
        }
        setShowDialog(true);
    };

    const handleCloseDialog = () => {
        setShowDialog(false);
        setEditingTeam(null);
        setFormData({ name: '', description: '', lead: '', members_count: 1, color: TEAM_COLORS[0] });
    };

    const handleSave = () => {
        if (editingTeam) {
            updateMutation.mutate({ id: editingTeam.id, data: formData });
        } else {
            createMutation.mutate(formData);
        }
    };

    const getTeamReleases = (teamId) => {
        return releases.filter(r => r.team_id === teamId);
    };

    const filteredTeams = teams.filter(team =>
        !searchQuery || team.name.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 p-6" dir={isRTL ? 'rtl' : 'ltr'}>
            <div className="max-w-7xl mx-auto">
                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                    <div>
                        <h1 className="text-3xl font-bold text-slate-800">{t('teams')}</h1>
                        <p className="text-slate-500 mt-1">{t('manageTeams')}</p>
                    </div>
                    <Button
                        onClick={() => handleOpenDialog()}
                        className="bg-indigo-600 hover:bg-indigo-700 gap-2"
                    >
                        <Plus className="w-4 h-4" />
                        {t('newTeam')}
                    </Button>
                </div>

                {/* Search */}
                <div className="relative max-w-md mb-6">
                    <Search className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400`} />
                    <Input
                        placeholder={t('searchTeams')}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className={isRTL ? 'pr-10' : 'pl-10'}
                    />
                </div>

                {/* Teams Grid */}
                {isLoading ? (
                    <div className="flex items-center justify-center h-64">
                        <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
                    </div>
                ) : filteredTeams.length === 0 ? (
                    <div className="text-center py-16">
                        <Users className="w-16 h-16 mx-auto text-slate-300 mb-4" />
                        <h3 className="text-lg font-medium text-slate-600">{t('noTeamsFound')}</h3>
                        <p className="text-slate-400 mt-1">{t('createFirstTeam')}</p>
                        <Button
                            onClick={() => handleOpenDialog()}
                            className="mt-4 bg-indigo-600 hover:bg-indigo-700"
                        >
                            <Plus className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
                            {t('createTeam')}
                        </Button>
                    </div>
                ) : (
                    <motion.div
                        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                    >
                        <AnimatePresence>
                            {filteredTeams.map((team, index) => {
                                const teamReleases = getTeamReleases(team.id);
                                const activeReleases = teamReleases.filter(r =>
                                    !['deployed', 'cancelled'].includes(r.status)
                                );

                                return (
                                    <motion.div
                                        key={team.id}
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        exit={{ opacity: 0, scale: 0.95 }}
                                        transition={{ delay: index * 0.05 }}
                                    >
                                        <Card className="overflow-hidden hover:shadow-lg transition-shadow">
                                            <div
                                                className="h-2"
                                                style={{ backgroundColor: team.color || '#6366f1' }}
                                            />
                                            <CardHeader className="pb-3">
                                                <div className="flex items-start justify-between">
                                                    <div className="flex items-center gap-3">
                                                        <div
                                                            className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold"
                                                            style={{ backgroundColor: team.color || '#6366f1' }}
                                                        >
                                                            {team.name.charAt(0).toUpperCase()}
                                                        </div>
                                                        <div>
                                                            <CardTitle className="text-lg">{team.name}</CardTitle>
                                                            {team.lead && (
                                                                <p className="text-sm text-slate-500 flex items-center gap-1 mt-1">
                                                                    <User className="w-3 h-3" />
                                                                    {team.lead}
                                                                </p>
                                                            )}
                                                        </div>
                                                    </div>
                                                    <div className="flex gap-1">
                                                        <Button
                                                            variant="ghost"
                                                            size="icon"
                                                            onClick={() => handleOpenDialog(team)}
                                                        >
                                                            <Edit className="w-4 h-4 text-slate-400" />
                                                        </Button>
                                                        <Button
                                                            variant="ghost"
                                                            size="icon"
                                                            onClick={() => deleteMutation.mutate(team.id)}
                                                        >
                                                            <Trash2 className="w-4 h-4 text-rose-400" />
                                                        </Button>
                                                    </div>
                                                </div>
                                            </CardHeader>
                                            <CardContent>
                                                {team.description && (
                                                    <p className="text-sm text-slate-500 mb-4 line-clamp-2">
                                                        {team.description}
                                                    </p>
                                                )}
                                                <div className="flex items-center justify-between text-sm">
                                                    <div className="flex items-center gap-1 text-slate-500">
                                                        <Users className="w-4 h-4" />
                                                        <span>{team.members_count || 0} {t('members')}</span>
                                                    </div>
                                                    <div className="text-slate-500">
                                                        {activeReleases.length} {t('activeReleases')}
                                                    </div>
                                                </div>
                                            </CardContent>
                                        </Card>
                                    </motion.div>
                                );
                            })}
                        </AnimatePresence>
                    </motion.div>
                )}

                {/* Dialog */}
                <Dialog open={showDialog} onOpenChange={setShowDialog}>
                    <DialogContent className="sm:max-w-md">
                        <DialogHeader>
                            <DialogTitle>
                                {editingTeam ? t('editTeam') : t('createNewTeam')}
                            </DialogTitle>
                        </DialogHeader>
                        <div className="space-y-4 py-4">
                            <div className="space-y-2">
                                <Label htmlFor="name">{t('teamName')} *</Label>
                                <Input
                                    id="name"
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    placeholder="e.g., Frontend Team"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="description">{t('description')}</Label>
                                <Textarea
                                    id="description"
                                    value={formData.description}
                                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                                    placeholder="Team description..."
                                    rows={2}
                                />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label htmlFor="lead">{t('teamLead')}</Label>
                                    <Input
                                        id="lead"
                                        value={formData.lead}
                                        onChange={(e) => setFormData({ ...formData, lead: e.target.value })}
                                        placeholder="e.g., John Doe"
                                    />
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="members">{t('membersCount')}</Label>
                                    <Input
                                        id="members"
                                        type="number"
                                        min="1"
                                        value={formData.members_count}
                                        onChange={(e) => setFormData({ ...formData, members_count: parseInt(e.target.value) || 1 })}
                                    />
                                </div>
                            </div>
                            <div className="space-y-2">
                                <Label>{t('teamColor')}</Label>
                                <div className="flex flex-wrap gap-2">
                                    {TEAM_COLORS.map(color => (
                                        <button
                                            key={color}
                                            type="button"
                                            className={cn(
                                                "w-8 h-8 rounded-full transition-transform hover:scale-110",
                                                formData.color === color && "ring-2 ring-offset-2 ring-slate-400"
                                            )}
                                            style={{ backgroundColor: color }}
                                            onClick={() => setFormData({ ...formData, color })}
                                        />
                                    ))}
                                </div>
                            </div>
                        </div>
                        <div className="flex justify-end gap-3">
                            <Button variant="outline" onClick={handleCloseDialog}>
                                {t('cancel')}
                            </Button>
                            <Button
                                onClick={handleSave}
                                disabled={!formData.name || createMutation.isPending || updateMutation.isPending}
                                className="bg-indigo-600 hover:bg-indigo-700"
                            >
                                {(createMutation.isPending || updateMutation.isPending) ? (
                                    <Loader2 className="w-4 h-4 animate-spin" />
                                ) : (
                                    <>
                                        <Save className={`w-4 h-4 ${isRTL ? 'ml-2' : 'mr-2'}`} />
                                        {editingTeam ? t('update') : t('createTeam')}
                                    </>
                                )}
                            </Button>
                        </div>
                    </DialogContent>
                </Dialog>
            </div>
        </div>
    );
}
